services:
  # MongoDB for local development
  mongodb:
    image: mongo:6.0
    container_name: voice-agent-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=voice_agent
    volumes:
      - mongodb_data:/data/db
    networks:
      - voice-agent-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: voice-agent-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - voice-agent-network
    restart: unless-stopped

  # API Service with PROPERLY FORMATTED environment variables
  api-service:
    build:
      context: ./ecs-api-service
      dockerfile: Dockerfile
    container_name: voice-agent-api
    volumes:
      - ./ecs-api-service/static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
      - HOST=${HOST}
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - PYTHONPATH=${PYTHONPATH}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - DOCUMENTDB_HOST=${DOCUMENTDB_HOST}
      - DOCUMENTDB_PORT=${DOCUMENTDB_PORT}
      - DOCUMENTDB_DATABASE=${DOCUMENTDB_DATABASE}
      - DOCUMENTDB_USERNAME=${DOCUMENTDB_USERNAME}
      - DOCUMENTDB_PASSWORD=${DOCUMENTDB_PASSWORD}
      - DOCUMENTDB_SSL=${DOCUMENTDB_SSL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
      - ELEVENLABS_VOICE_SPEED=${ELEVENLABS_VOICE_SPEED}
      - "ELEVENLABS_VOICE_SETTINGS=${ELEVENLABS_VOICE_SETTINGS}"
      - VOICE_STABILITY=${VOICE_STABILITY}
      - VOICE_SIMILARITY_BOOST=${VOICE_SIMILARITY_BOOST}
      - VOICE_STYLE=${VOICE_STYLE}
      - USE_SPEAKER_BOOST=${USE_SPEAKER_BOOST}
      - DEFAULT_VOICE_ID=${DEFAULT_VOICE_ID}
      - LYZR_API_BASE_URL=${LYZR_API_BASE_URL}
      - LYZR_CONVERSATION_AGENT_ID=${LYZR_CONVERSATION_AGENT_ID}
      - LYZR_SUMMARY_AGENT_ID=${LYZR_SUMMARY_AGENT_ID}
      - LYZR_API_KEY=${LYZR_API_KEY}
      - LYZR_USER_API_KEY=${LYZR_USER_API_KEY}
      - CAPSULE_API_TOKEN=${CAPSULE_API_TOKEN}
      - CAPSULE_API_URL=${CAPSULE_API_URL}
      - GOOGLE_CALENDAR_CLIENT_ID=${GOOGLE_CALENDAR_CLIENT_ID}
      - GOOGLE_CALENDAR_CLIENT_SECRET=${GOOGLE_CALENDAR_CLIENT_SECRET}
      - SES_REGION=${SES_REGION}
      - FROM_EMAIL=${FROM_EMAIL}
      - S3_BUCKET_AUDIO=${S3_BUCKET_AUDIO}
      - S3_BUCKET_RECORDINGS=${S3_BUCKET_RECORDINGS}
      - MAX_CONCURRENT_CALLS=${MAX_CONCURRENT_CALLS}
      - CALL_TIMEOUT_SECONDS=${CALL_TIMEOUT_SECONDS}
      - MAX_CALL_ATTEMPTS=${MAX_CALL_ATTEMPTS}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS}
      - SESSION_CACHE_TTL=${SESSION_CACHE_TTL}
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT}
      - BUSINESS_START_HOUR=${BUSINESS_START_HOUR}
      - BUSINESS_END_HOUR=${BUSINESS_END_HOUR}
      - BUSINESS_DAYS=${BUSINESS_DAYS}
      - BUSINESS_TIMEZONE=${BUSINESS_TIMEZONE}
      - STT_MODEL=${STT_MODEL}
      - DEEPGRAM_TIMEOUT=${DEEPGRAM_TIMEOUT}
      - ELEVENLABS_TIMEOUT=${ELEVENLABS_TIMEOUT}
      - LYZR_TIMEOUT=${LYZR_TIMEOUT}
      - WEBSOCKET_TIMEOUT=${WEBSOCKET_TIMEOUT}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - SQS_VISIBILITY_TIMEOUT=${SQS_VISIBILITY_TIMEOUT}
      - SQS_WAIT_TIME=${SQS_WAIT_TIME}
      - ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME}
      - ECS_SERVICE_NAME=${ECS_SERVICE_NAME}
    depends_on:
      - mongodb
      - redis
    networks:
      - voice-agent-network
    restart: unless-stopped

  # Worker Service with matching environment
  worker-service:
    build:
      context: ./ecs-worker-service
      dockerfile: Dockerfile
    container_name: voice-agent-worker
    environment:
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
      - PYTHONPATH=${PYTHONPATH}
      - DOCUMENTDB_HOST=${DOCUMENTDB_HOST}
      - DOCUMENTDB_PORT=${DOCUMENTDB_PORT}
      - DOCUMENTDB_DATABASE=${DOCUMENTDB_DATABASE}
      - DOCUMENTDB_USERNAME=${DOCUMENTDB_USERNAME}
      - DOCUMENTDB_PASSWORD=${DOCUMENTDB_PASSWORD}
      - DOCUMENTDB_SSL=${DOCUMENTDB_SSL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - LYZR_USER_API_KEY=${LYZR_USER_API_KEY}
      - LYZR_SUMMARY_AGENT_ID=${LYZR_SUMMARY_AGENT_ID}
      - CAPSULE_API_TOKEN=${CAPSULE_API_TOKEN}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - BUSINESS_START_HOUR=${BUSINESS_START_HOUR}
      - BUSINESS_END_HOUR=${BUSINESS_END_HOUR}
      - BUSINESS_DAYS=${BUSINESS_DAYS}
      - BUSINESS_TIMEZONE=${BUSINESS_TIMEZONE}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL}
      - SQS_VISIBILITY_TIMEOUT=${SQS_VISIBILITY_TIMEOUT}
      - SQS_WAIT_TIME=${SQS_WAIT_TIME}
      - MAX_CALL_ATTEMPTS=${MAX_CALL_ATTEMPTS}
    depends_on:
      - mongodb
      - redis
    networks:
      - voice-agent-network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  voice-agent-network:
    driver: bridge
